version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10

    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      majors:
        patterns: ["*"]
        update-types: ["major"]

    ignore:
      - dependency-name: "EPPlus"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"